name: Sync Fork

on:
  schedule:
    - cron: '50 0 * * *'
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: zwping/fork-sync@v1.6.5
        with:
          owner: aiboboxx
          base: main
          head: main
